[package]
name = "kerosine"
version = "0.1.0"
edition = "2021"

[dependencies]
candle-core = "0.6.0"
candle-nn = "0.6.0"
candle-examples = "0.6.0"
image = "0.25.2"

[features]
metal = ["candle-core/metal", "candle-nn/metal"]
cuda = ["candle-core/cuda", "candle-nn/cuda"]
